# Generated by Django 5.2.7 on 2025-10-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand'], name='products_pr_categor_1e5c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'status'], name='products_pr_price_cd05f7_idx'),
        ),
    ]
